Pages/Admin/Order.cshtml.cs
using ECommerceWeb.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ECommerceWeb.Pages.Admin
{
    public class OrderModel : PageModel
    {
        private readonly DemoProjectContext _context;

        public OrderModel (DemoProjectContext context)
        {
            _context = context;
        }

        public IEnumerable<Order> datalist { get; set; } //this is for list


        [BindProperty]
        public Order order { get; set; }


        #region----GET METHOD-----
        public IActionResult OnGet(int? id)
        {
            datalist = _context.Orders.Where(e => e.IsDeleted == false).ToList();
            order = new Order();
            if (id.HasValue)
            {
                var co = _context.Orders.Where(e => e.Id == id && e.IsDeleted == false).FirstOrDefault();
                if (co == null)
                {
                    return NotFound();
                }
                order = co;
            }


            return Page();

        }
        #endregion


        #region--POST METHOD--
        public IActionResult OnPost()
        {
            if (order.Id > 0)//Update
            {
                var co = _context.Orders.AsNoTracking().Where(e => e.Id == order.Id && e.IsDeleted == false).FirstOrDefault();
                if (co == null)
                {
                    return NotFound();
                }


                order.IsDeleted = co.IsDeleted;
                _context.Orders.Update(order);
                _context.SaveChanges();
                TempData["info"] = "Your Data update Successfully";

            }
            else
            {
                try
                {

                    order.IsDeleted = false;
                    _context.Orders.Add(order);
                    _context.SaveChanges();
                    TempData["success"] = "data saved";
                }
                catch (Exception ex) { }
            }
            return RedirectToPage();

        }

        #endregion

        #region---DELETE METHOD--

        public IActionResult OnPostDelete(int id)
        {
            var co = _context.Orders.Where(e => e.Id == id && e.IsDeleted == false).FirstOrDefault();
            if (co == null)
            {
                return NotFound();
            }
            co.IsDeleted = true;
            _context.Orders.Update(co);
            _context.SaveChanges();
            TempData["success"] = "data deleted";
            return RedirectToPage();

        }

        #endregion



    }
}

Pages/Admin/ProductSize.cshtml.cs
using ECommerceWeb.Model;
using ECommerceWeb.Pages.Admin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace ECommerceWeb.Pages.Admin
{
    public class ProductSizeModel : PageModel
    {
        private readonly DemoProjectContext _context;

        public ProductSizeModel(DemoProjectContext context)
        {
            _context = context;
        }


        public IEnumerable<ProductSize> datalist { get; set; } //this is for list



        [BindProperty]
        public ProductSize productSize { get; set; }



        #region----GET METHOD-----
        public IActionResult OnGet(int? id)
        {
            datalist = _context.ProductSizes.Where(e => e.IsDeleted == false).ToList();
            productSize = new ProductSize();
            if (id.HasValue)
            {
                var co = _context.ProductSizes.Where(e => e.Id == id && e.IsDeleted == false).FirstOrDefault();
                if (co == null)
                {
                    return NotFound();
                }
                productSize = co;
            }


            return Page();

        }
        #endregion


        #region--POST METHOD--
        public IActionResult OnPost()
        {
            if (productSize.Id > 0)//Update
            {
                var co = _context.ProductSizes.AsNoTracking().Where(e => e.Id == productSize.Id && e.IsDeleted == false).FirstOrDefault();
                if (co == null)
                {
                    return NotFound();
                }


                productSize.IsDeleted = co.IsDeleted;
                _context.ProductSizes.Update(productSize);
                _context.SaveChanges();
                TempData["info"] = "Your Data update Successfully";

            }
            else
            {
                try
                {

                    productSize.IsDeleted = false;
                    _context.ProductSizes.Add(productSize);
                    _context.SaveChanges();
                    TempData["success"] = "data saved";
                }
                catch (Exception ex) { }
            }
            return RedirectToPage();

        }

        #endregion

        #region---DELETE METHOD--

        public IActionResult OnPostDelete(int id)
        {
            var co = _context.ProductSizes.Where(e => e.Id == id && e.IsDeleted == false).FirstOrDefault();
            if (co == null)
            {
                return NotFound();
            }
            co.IsDeleted = true;
            _context.ProductSizes.Update(co);
            _context.SaveChanges();
            TempData["success"] = "data deleted";
            return RedirectToPage();

        }

        #endregion



    }
}

Pages/Metronic-Shop/MyAccount.cshtml.cs
using ECommerceWeb.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;

namespace ECommerceWeb.Pages.Metronic_Shop
{
    public class MyAccountModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [BindProperty]
        public string CartItems { get; set; }

        public List<CartItem> OrderItems { get; set; }

        private readonly DemoProjectContext _context;

        public MyAccountModel (DemoProjectContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (string.IsNullOrEmpty(CartItems))
            {
                return Page();
            }

            OrderItems = JsonSerializer.Deserialize<List<CartItem>>(CartItems);

            Order order = new Order
            {
                OrderStatus = 1,
                OrderDate = DateTime.Now,
                OrderNumber = GenerateOrderNumber(10),
                CustomerId = 1,
                IsDeleted = false
            };
            _context.Orders.Add(order);
            _context.SaveChanges();

            var OrderId = _context.Orders
                                  .Where(x => x.OrderNumber == order.OrderNumber)
                                  .Select(x => x.Id)
                                  .FirstOrDefault();

            foreach (var itm in OrderItems)
            {
                OrderItem orderitem = new OrderItem
                {
                    ItemQuantity = itm.quantity,
                    ProductId = itm.productid,
                    OrderId = OrderId,
                    IsDeleted = false
                };
                _context.OrderItems.Add(orderitem);
                _context.SaveChanges();
            }

            CartItems = string.Empty;

            return RedirectToPage("OrderConfirmation");
        }

        private static string GenerateOrderNumber(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            Random random = new Random();
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public class CartItem
        {
            public string? image { get; set; }
            public string? name { get; set; }
            public string? price { get; set; }
            public int? quantity { get; set; }
            public int? productid { get; set; }
            public int? customerId { get; set; }
        }
    }
}

Pages/Metronic-Shop/Order.cshtml.cs
using ECommerceWeb.Model;
using ECommerceWeb.VModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ECommerceWeb.Pages.Metronic_Shop
{
    public class OrderModel : PageModel
    {
        private readonly DemoProjectContext _context;

        public OrderModel(DemoProjectContext context)
        {
            _context = context;
        }

        public IEnumerable<Order> OrderItems { get; set; } // This is for list of order items
        public IEnumerable<Product> Products { get; set; } // This is for Product

        [BindProperty]
        public Order Order { get; set; }

        #region----GET METHOD-----
        public IActionResult OnGet(int? id)
        {
            Products = _context.Products.Where(e => e.IsDeleted == false).ToList();

            OrderItems = _context.Orders.Where(e => e.IsDeleted == false).Select(e => new Order
            {
                Id = e.Id,
                CustomerId = e.CustomerId,
                OrderNumber = e.OrderNumber, 
                OrderDate = e.OrderDate,
                OrderStatus = e.OrderStatus,
            }).ToList();

            Order = new Order();
            if (id.HasValue)
            {
                var orderItem = _context.Orders.Where(e => e.Id == id && e.IsDeleted == false).FirstOrDefault();
                if (orderItem == null)
                {
                    return NotFound();
                }
                Order = orderItem;
            }

            return Page();
        }
        #endregion

        #region--POST METHOD--
        public IActionResult OnPost()
        {
            if (Order.Id > 0) // Update
            {
                var existingOrderItem = _context.Orders.AsNoTracking().Where(e => e.Id == Order.Id && e.IsDeleted == false).FirstOrDefault();
                if (existingOrderItem == null)
                {
                    return NotFound();
                }

                Order.IsDeleted = existingOrderItem.IsDeleted;
                _context.Orders.Update(Order);
                _context.SaveChanges();
                TempData["info"] = "Your data updated successfully.";
            }
            else
            {
                try
                {
                    Order.IsDeleted = false;
                    _context.Orders.Add(Order);
                    _context.SaveChanges();
                    TempData["success"] = "Data saved.";
                }
                catch (Exception ex)
                {
                    // Log the exception
                    TempData["error"] = "An error occurred while saving data.";
                }
            }
            return RedirectToPage();
        }
        #endregion

        #region---DELETE METHOD---
        public IActionResult OnPostDelete(int id)
        {
            var orderItem = _context.Orders.Where(e => e.Id == id && e.IsDeleted == false).FirstOrDefault();
            if (orderItem == null)
            {
                return NotFound();
            }
            orderItem.IsDeleted = true;
            _context.Orders.Update(orderItem);
            _context.SaveChanges();
            TempData["success"] = "Data deleted.";
            return RedirectToPage();
        }
        #endregion
    }
}

Pages/Metronic-Shop/PaymentOptions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace ECommerceWeb.Pages.Metronic_Shop
{
    public class PaymentOptionsModel : PageModel
    {
        [BindProperty]
        public List<PaymentMethod> PaymentList { get; set; } = new List<PaymentMethod>();

        [BindProperty]
        public PaymentMethod NewPayment { get; set; }

        public void OnGet()
        {
            // Sample data, replace with actual data retrieval logic
            PaymentList = new List<PaymentMethod>
            {
                new PaymentMethod { Id = 1, CardHolderName = "Sidhart Malhotra", Last4Digits = "1234", ExpiryMonth = "12", ExpiryYear = "2024" },
                new PaymentMethod { Id = 2, CardHolderName = "Aanand Shroff", Last4Digits = "5678", ExpiryMonth = "06", ExpiryYear = "2025" },
                new PaymentMethod { Id = 3, CardHolderName = "Honey Bee", Last4Digits = "4233", ExpiryMonth = "26", ExpiryYear = "2021"},
                new PaymentMethod { Id = 4, CardHolderName = "Parmish Verma", Last4Digits = "8654", ExpiryMonth = "27", ExpiryYear = "2028"},
                new PaymentMethod { Id = 5, CardHolderName = "NeerajChopra", Last4Digits = "3113", ExpiryMonth = "26", ExpiryYear = "2020"},
                new PaymentMethod { Id = 6, CardHolderName = "Jennifer Winget", Last4Digits = "6533", ExpiryMonth = "54", ExpiryYear = "2020"},
                new PaymentMethod { Id = 7, CardHolderName = "Zain Imam", Last4Digits = "9773", ExpiryMonth = "22", ExpiryYear = "2024"},
                new PaymentMethod { Id = 8, CardHolderName = "Roshani Jha", Last4Digits = "0965", ExpiryMonth = "23", ExpiryYear = "2097"},
                new PaymentMethod { Id = 9, CardHolderName = "Geni Gony", Last4Digits = "4334", ExpiryMonth = "01", ExpiryYear = "2027"},
                new PaymentMethod { Id =10, CardHolderName = "Manisha Jha", Last4Digits = "5532", ExpiryMonth = "15", ExpiryYear = "2098"}


            };
        }

        public IActionResult OnPostAdd()
        {
            if (ModelState.IsValid)
            {
                // Logic to add the new payment method to the database or in-memory list
                PaymentList.Add(new PaymentMethod
                {
                    Id = PaymentList.Count + 1, // Sample ID generation logic
                    CardHolderName = NewPayment.CardHolderName,
                    Last4Digits = NewPayment.CardNumber[^4..],
                    ExpiryMonth = NewPayment.ExpiryMonth,
                    ExpiryYear = NewPayment.ExpiryYear
                });

                // Reset the NewPayment property to clear the form
                NewPayment = new PaymentMethod();
            }

            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            // Logic to delete the payment method from the database or in-memory list
            var paymentMethod = PaymentList.Find(p => p.Id == id);
            if (paymentMethod != null)
            {
                PaymentList.Remove(paymentMethod);
            }

            return Page();
        }
    }

    public class PaymentMethod
    {
        public int Id { get; set; }

        [Required]
        public string CardHolderName { get; set; }

        [Required]
        [CreditCard]
        public string CardNumber { get; set; }

        [Required]
        [Range(1, 12)]
        public string ExpiryMonth { get; set; }

        [Required]
        [Range(2022, 2030)]
        public string ExpiryYear { get; set; }

        [Required]
        [StringLength(4, MinimumLength = 3)]
        public string Cvv { get; set; }

        // Additional properties to display masked card number
        public string Last4Digits { get; set; }
    }
}

Pages/Metronic-Shop/Prime.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerceWeb.Pages.Metronic_Shop
{
    public class PrimeModel : PageModel
    {
        [BindProperty]
        public bool IsPrimeMember { get; set; }

        public void OnGet()
        {
            // Simulate fetching user details from a database
            // For demonstration, let's assume the user is not a Prime member
            IsPrimeMember = false;
        }

        public async Task<IActionResult> OnPostJoinPrimeAsync()
        {
            // Simulate updating the user's Prime membership status in the database
            // For demonstration, let's assume the operation is successful

            IsPrimeMember = true;

            // You would typically update the database here
            // e.g., await _database.UpdateUserPrimeStatusAsync(UserId, true);

            return RedirectToPage();
        }
    }
}

Pages/Metronic-Shop/PaymentOptions.cshtml
@page
@model ECommerceWeb.Pages.Metronic_Shop.PaymentOptionsModel
@{
    ViewData["Title"] = "Payment Options";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Options</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="path/to/bootstrap.css">

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f2f5;
            margin: 0;
            padding: 0;
        }

        /* .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        } */
        h2{
           
           /*  background: linear-gradient(135deg, #f9d423, #ff4e50); */
            
            background: linear-gradient(135deg, #136a8a, #f9d423);
            
            box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);
            color:white;
            text-align:center;
            padding: 10px;
            border-radius:10px;
        }
        h2:hover{
                background-color: #9900cc;
        }
        header {
            text-align: center;
            /* margin-bottom: 20px; */
            box-shadow: inset 0 0 10px #4CAF50; /* inner shadow */
            color: white;
            /* padding: 10px; */
            background-color: #4CAF50;
            border-radius: 15px;
        }

        nav ul {
            display: flex;
            justify-content: space-around;
            list-style: none;
            padding: 10px 0;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin: 0;
            border-radius: 0 0 10px 10px;
        }

            nav ul li {
                flex: 1;
                text-align: center;
            }

                nav ul li a {
                    display: block;
                    padding: 10px;
                    text-decoration: none;
                    color: #333;
                    font-weight: bold;
                    transition: background-color 0.3s;
                }

                    nav ul li a:hover {
                        background-color: #e0e0e0;
                    }

        .payment-card {
            margin: 20px 0;
            padding: 20px;
            background: linear-gradient(135deg, #e0f7fa, #e1bee7);
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            display: flex;
            justify-content: space-between;
            align-items: center;
            transition: transform 0.3s;
        }

            .payment-card:hover {
                transform: translateY(-5px);
            }

        .payment-details h3 {
            margin: 0;
            color: #333;
        }

        .payment-details p {
            margin: 5px 0 0;
            color: #666;
        }

        .payment-actions button {
            background-color: #f44336;
            border: none;
            color: white;
            padding: 10px 20px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

            .payment-actions button:hover {
                background-color: #e53935;
            }

        .payment-form {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 15px;
        }

            .form-group label {
                display: block;
                margin-bottom: 5px;
                font-weight: bold;
                color: #333;
            }

        .form-control {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            transition: border-color 0.3s, box-shadow 0.3s;
        }

            .form-control:focus {
                border-color: #4CAF50;
                box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);
            }

        .btn-primary {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 10px 0;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

            .btn-primary:hover {
                background-color: #ff66d9;
            }
    </style>
</head>
<body>
         <nav>
            <ul>
                <li><a href="YourOrders"><i class="fas fa-box"></i> Your Orders</a></li>
                <li><a href="#login-security"><i class="fas fa-user-shield"></i> Login & Security</a></li>
                <li><a href="prime"><i class="fas fa-crown"></i> Prime</a></li>
                <li><a href="youraddresses"><i class="fas fa-map-marker-alt"></i> Your Addresses</a></li>
                <li><a href="paymentoptions"><i class="fas fa-credit-card"></i> Payment Options</a></li>
            </ul>
        </nav>
    <div class="content-wrapper">
        

            <section id="add-payment-method">
                <h2>Add a New Payment Method</h2>
                <form method="post" class="payment-form">
                    <div class="form-group">
                        <label for="CardHolderName">Card Holder Name:</label>
                        <input type="text" id="CardHolderName" asp-for="NewPayment.CardHolderName" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label for="CardNumber">Card Number:</label>
                        <input type="text" id="CardNumber" asp-for="NewPayment.CardNumber" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label for="ExpiryMonth">Expiry Month:</label>
                        <input type="text" id="ExpiryMonth" asp-for="NewPayment.ExpiryMonth" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label for="ExpiryYear">Expiry Year:</label>
                        <input type="text" id="ExpiryYear" asp-for="NewPayment.ExpiryYear" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label for="Cvv">CVV:</label>
                        <input type="text" id="Cvv" asp-for="NewPayment.Cvv" class="form-control" required />
                    </div>
                    <button class="btn btn-primary" type="submit" asp-page-handler="Add">Add Payment Method</button>
                </form>
            </section>
            <section id="payment-methods">
                <h2>Your Payment Methods</h2>
                @if (Model.PaymentList.Count > 0)
                {
                    foreach (var payment in Model.PaymentList)
                    {
                        <div class="payment-card">
                            <div class="payment-details">
                                <h3>@payment.CardHolderName</h3>
                                <p>**** **** **** @payment.Last4Digits</p>
                                <p>Expires: @payment.ExpiryMonth/@payment.ExpiryYear</p>
                            </div>
                            <div class="payment-actions">
                                <form method="post">
                                    <button type="submit" asp-page-handler="Delete" asp-route-id="@payment.Id">Delete</button>
                                </form>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p>No payment methods found. Add a new payment method below.</p>
                }
            </section>
           
       
    </div>
</body>
</html>

Pages/Metronic-Shop/ProductSize.cshtml
@page
@model ECommerceWeb.Pages.Metronic_Shop.ProductSizeModel
@{
    ViewBag.Title = "ProductSize";
 }
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <!-- 1st container fluid start-->
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>ProductSizes</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-page="index">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div><!-- / 1st container-fluid ends-->
    </section>


    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- Countrise validation -->
                <div class="card card-primary card-outline card-info">
                    <h5 class="ml-3">Product Size</h5>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="post">
                        <input type="hidden" asp-for="productSize.Id" />
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-lg-4">
                                    <label class="ml-2">Name</label>
                                    <input type="text" asp-for="productSize.Name" class="form-control" placeholder="Short Name" required>
                                </div>
                            </div>


                            <!-- /.card-body -->
                            <div class="text-center mt-3">

                                @if (Model.productSize.Id != 0)
                                {
                                    <button type="submit" class="btn btn-info">UPDATE</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-info">SUBMIT</button>

                                }
                            </div>

                        </div>

                    </form>


                </div>




                <form method="post">

                    <div class="card-body card card-outline card-success pl-1">
                        <div class="card-header">

                            <h3 class="mr-2">Product Size Datalist</h3>
                        </div>

                        <table id="example1" class="table table-bordered table-striped">
                            <!--For drop menu-->
                            <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Action</th>

                                </tr>
                            </thead>

                            <tbody>

                                @if (Model.datalist.Count() > 0)
                                {
                                    foreach (var item in Model.datalist)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Name</td>


                                            <td class="mr-5">
                                                <a asp-page="ProductSize" asp-route-id="@item.Id" class="btn btn-success">EDIT</a>


                                                <button asp-page-handler="Delete" asp-route-id="@item.Id"
                                                        onclick="return confirm('Are you sure you want to DELETE?')" class="btn btn-danger">
                                                    DELETE
                                                </button>

                                            </td>


                                        </tr>
                                    }
                                }



                                else
                                {

                                    <tr>No data found</tr>

                                }


                            </tbody>


                        </table>

                    </div>

                </form>


            </div>
        </div>
    </div>


</div>